apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: python-app
    labels:
        name: python-app
spec:
    replicas: 1
    selector:
        matchLabels:
            name: python-app
    template:
        metadata:
            labels:
                name: python-app
        spec:
            containers:
              - name: python-app
                image: python-custom:latest
        